name: Build and Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
    name: Build and test (Node ${{ matrix.node_version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['14', '16', '18']

    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Setup Node.js environment
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm

      - name: Update npm
        run: npm i -g npm@latest

      - name: Install dependencies and test
        run: npm cit
