name: Build and Test CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
    name: Build and test (Node ${{ matrix.node.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - name: LTS
            version: lts/*
          - name: Current
            version: node
          - name: Previous LTS
            version: lts/-1
    steps:
      - name: Check out source code
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Setup Node.js environment
        uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
        with:
          node-version: ${{ matrix.node.version }}
          cache: npm

      - name: Install dependencies and test
        run: npm cit
