name: Publish npm package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3.5.1
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          cache: npm
      - run: npm i -g npm@latest
      - run: npm cit
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
